# Import file and theme
[general]
import = ["./themes/gruvbox_dark.toml"]
live_config_reload = true

[window]
opacity = 1.0
dimensions = { columns = 140, lines = 40 }
position = { x = 100, y = 50 }
startup_mode = "Windowed"
padding = { x = 5, y = 5 }
title = "Alacritty"

[cursor]
style = { shape = "Beam", blinking = "On" }

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }

[env]
TERM = "xterm-256color"
